### ISSUE TITLE
Please add support for this locale. It's for English India

### ISSUE THREAD

**Issue by its-ashu-otf** [IamCarron/DVWA-Script#4]
locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

**Comment by IamCarron** [comment]
I am seeing that in your LANGUAGE= it is empty, so it only shows the region, could you tell me how you modified this to reproduce the error in local?

**Comment by its-ashu-otf** [comment]
This is a fresh install of kali with English India Selected sir

**Comment by IamCarron** [comment]
New, version released, could you try it?

**Comment by its-ashu-otf** [comment]
Sure

**Comment by its-ashu-otf** [comment]
It works now. Thanks
